### ISSUE TITLE
hbase-hdfs demo gcp bug

### ISSUE THREAD

**Issue by snocke** [stackabletech/stackablectl#123]
## Description

The demo hbase-hdfs does not work on a GCP cluster. 

We want to investigate the reason. The demo works locally on a KIND cluster.

`2022-09-21 13:59:24,792 WARN  [Thread-71] hdfs.DataStreamer (DataStreamer.java:getPinnings(1828)) - These favored nodes were specified but not chosen: [hbase-regionserver-default-0.hbase-regionserver-default.default.svc.cluster.local:16020] Specified favored nodes: [hbase-regionserver-default-0.hbase-regionserver-default.default.svc.cluster.local:16020]
2022-09-21 13:59:24,842 WARN  [Thread-57] hdfs.DataStreamer (DataStreamer.java:run(823)) - DataStreamer Exception
org.apache.hadoop.ipc.RemoteException(java.io.IOException): File /data/hfile/_temporary/0/_temporary/attempt_local1978330863_0001_r_000000_0/end_station_id/9fce3807dc09483f98c629db70e9b2d0 could only be written to 0 of the 1 minReplication nodes. There are 1 datanode(s) running and 0 node(s) are excluded in this operation.
        at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:2315)
        at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.chooseTargetForNewBlock(FSDirWriteFileOp.java:294)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:2960)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:904)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:593)
        at 
`

## Strategies

nedd to be defined

## Acceptance criteria

demo works on GCP

**Comment by snocke** [comment]
For a solution we depend on the progress of https://issues.apache.org/jira/browse/HDFS-16577

**Comment by lfrancke** [comment]
We have listener support now. This should hopefully be fixed.
